language: node_js
node_js:
- 4.2.1
install:
- npm install psi -g
- npm install webpagetest -g
script:
- psi psi.kitconcept.com --threshold 99
- webpagetest test http://psi.kitconcept.com  -k $WPT_API_KEY --poll --specs testspecs.json --reporter spec
notifications:
  email:
  - tisto@plone.org
env:
  global:
    secure: qlP9/bsYvgu49v3V7BTQ0uKe/0WaPr3AokhXDDECcc1SvbhQqfbU5/xPtaExlntHM1zesFM9WK667zWA2OnZbA3HAeQOHVuaipCJejK6yn/cxW5/JA2v0JlHrVQ357i8emSH8VwckSbweWrsDYA1YTRY7xs91sFGKTNYLiWUlc3ZxFq71MYvBC9fbTFPdqkZzW0tIpIFVtwO7BRgYtYviIkL1FygyxNPEEt4VHM/jG9l7NtEqi5LIKb8amfcMM4gRmdbyleLQdjXs5F/MzE8v9RFXppuElWbdPHti48B1w89ba2FrJfXNmdL26zR/QxWrsjNn29lzxs3K9K2/ar3zQTOmVcltjF5bM1EbytINWnsdXVwKGAwt8cbseNcv/Q5P6CL6fBgmkbDNcSV4ZbVoFamRIeX1LAJC74INpA8Zid+ul2pdnnYVCOWY0MtXmHOigL/bHNcvrjrFEmX76GvJOT/twceEWHn/6O5s3LFySKzeYEW/NH+aW4ifFGHcTRxcjKhdEyAp2GEEjyinoDILdr8Ic2pzLUawkZOr6zGregXw679rvHHFhH9NITPJVdUsL9jQU1J6ZAXsBT1YxC8Jso/QHsulCCPvQeAGAi6ZwJWZGIOyyOJ5/mokkAMXBo70AdQiuA3s9wK+YrIRM0Q5TDWZcUTFgz1JvyA0YUKi58=
